name: 'Check Latest LTS'

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1.1.0
        with:
          version: lts
      - run: yarn install
      - run: yarn run build
      - name: custom action step
        id: main
        uses: ./
      - name: debug
        run: echo ${{ steps.main.outputs.version }}
